export const ADD_ITEM_TO_KART = "ADD_ITEM_TO_KART";
export const REMOVE_ITEM_FROM_KART = "REMOVE_ITEM_FROM_KART";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const SET_LOADING = "SET_LOADING";
